### ISSUE TITLE
Usage Problems

### ISSUE THREAD

**Issue by twobeass** [danielinux/ttybus#7]
Hi i just tried to use your Tool, but if i 
tty_bus -s /tmp/ttyS0mux

It just Outputs
Creating bus: /tmp/ttyS0mux

And never end... What am i doing wrong ? I just cloned the git used make and make install..
Thanks for an answer..
Tobi

**Comment by AccessArctic** [comment]
Hi
I got exactly the same situation that @twobeass, same problem (on a Raspberry Pi CM3)
Any ideas?

Thanks
